name: operatorsafe
description: "A flutter project for simplifying and assisting in lift planning for crane trucks"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_native_splash:
  color: "#F5C400"
  image: assets/images/crane-truck.png
  android: false
  ios: true
